FROM opensuse/tumbleweed

RUN zypper -n install \
        binutils clang9-devel cmake flex gcc-c++ llvm9-devel python3-Pebble python3-pytest python3-psutil unifdef \
        python3-pytest-flake8 \
        python3-flake8 \
        python3-flake8-builtins \
        python3-flake8-bugbear \
        python3-flake8-comprehensions\
        python3-flake8-import-order \
        python3-flake8-quotes
ENV LSAN_OPTIONS="detect_leaks=0"

WORKDIR /usr/src/cvise
VOLUME /usr/src/cvise
