FROM opensuse/tumbleweed

RUN zypper -n install \
        binutils clang10-devel cmake flex gcc-c++ llvm10-devel python3-Pebble python3-pytest unifdef python3-pip python3-psutil sqlite-devel git python3 \
        python3-pytest-flake8 \
        python3-flake8 \
        python3-flake8-builtins \
        python3-flake8-bugbear \
        python3-flake8-comprehensions\
        python3-flake8-import-order \
        python3-flake8-quotes
RUN pip install codecov pytest-cov
ENV LSAN_OPTIONS="detect_leaks=0"

WORKDIR /usr/src/cvise
VOLUME /usr/src/cvise
