FROM opensuse/tumbleweed

RUN zypper -n install \
        binutils clang9-devel cmake flex gcc-c++ llvm9-devel python3-Pebble python3-pytest python3-psutil unifdef
ENV LSAN_OPTIONS="detect_leaks=0"

WORKDIR /usr/src/cvise
VOLUME /usr/src/cvise
