name: test checkout without git
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed
    steps:
      - run: rpm -q git || echo "git not installed"
      - uses: actions/checkout@v6
      - run: ls -la
